# Generated by Django 3.0.6 on 2020-07-20 07:36

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+$', 'Problem code must be ^[a-z0-9]+$')])),
                ('description', ckeditor.fields.RichTextField()),
                ('input_format', ckeditor.fields.RichTextField()),
                ('constraints', ckeditor.fields.RichTextField()),
                ('output_format', ckeditor.fields.RichTextField()),
                ('types', models.CharField(max_length=50)),
                ('sample_input', ckeditor.fields.RichTextField()),
                ('sample_output', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
