# Generated by Django 3.0.6 on 2020-07-20 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$', 'Problem code cannot have white space and can have only hyphens between letters and numbers')]),
        ),
    ]
