# Generated by Django 3.0.6 on 2020-07-20 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20200720_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
