# Generated by Django 3.0.6 on 2020-07-21 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problem_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input1',
            field=ckeditor.fields.RichTextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input2',
            field=ckeditor.fields.RichTextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output1',
            field=ckeditor.fields.RichTextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output2',
            field=ckeditor.fields.RichTextField(default='Empty'),
        ),
    ]
