# Generated by Django 3.0.6 on 2020-07-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20200721_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
