# Generated by Django 3.0.6 on 2020-07-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_problem_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
